name: André Araiz
favicon: null
layout_spectrum: 0.622882786905393
typography_spectrum: 0.9506918450351804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#fafbea'
    - '#b86d36'
    - '#b0afa4'
    - '#666535'
  brandStrength: 0.5
  lightness: 0.7912861909717321
  saturation: 0.9726950216572732
  rhythmicContrast: 0.12592161470092833
purpose: []
